name: Deploy MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user --no-cache-dir Cython
          pip install --user -r requirements.txt
          pip install mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter mkdocs-pdf-export-plugin ipykernel
      - name: Discover typos with codespell
        run: |
          pip install codespell
          codespell --skip=".*,.git/*,*.csv,*.geojson,*.json,*.js,*.html,*cff,*.pdf" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs"
      - name: Build MkDocs site
        run: mkdocs build
      - name: deploy
        run: mkdocs gh-deploy --force
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
